"""empty message

Revision ID: 3754220ae4ac
Revises: 31817bd2e59c
Create Date: 2025-11-08 21:04:29.653447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3754220ae4ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TaskTBL', sa.Column('name', sa.String(), nullable=True))
    op.add_column('TaskTBL', sa.Column('startDate', sa.DateTime(), nullable=True))
    op.add_column('TaskTBL', sa.Column('endDate', sa.DateTime(), nullable=True))
    op.add_column('UserId', sa.Integer(), nullable=True),
    op.drop_column('UserTBL', 'UserName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserTBL', sa.Column('UserName', sa.VARCHAR(), nullable=True))
    op.drop_column('TaskTBL', 'endDate')
    op.drop_column('TaskTBL', 'startDate')
    op.drop_column('TaskTBL', 'name')
    # ### end Alembic commands ###
