"""Initial migration

Revision ID: 576782d4bc02
Revises: 9c37c40c88c3
Create Date: 2025-11-14 21:01:39.587887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576782d4bc02'
down_revision: Union[str, Sequence[str], None] = '9c37c40c88c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TaskTBL', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TaskTBL', 'completed')
    # ### end Alembic commands ###
