"""empty message

Revision ID: fc9d77f2f159
Revises: 
Create Date: 2025-11-08 18:49:09.031711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9d77f2f159'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserTBL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(), nullable=True),
    sa.Column('DeleteFlg', sa.Boolean(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserTBL_id'), 'UserTBL', ['id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    op.create_table('TaskTBL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('DeleteFlg', sa.Boolean(), nullable=True),
    sa.Column('LastModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['UserTBL.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TaskTBL_id'), 'TaskTBL', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TaskTBL_id'), table_name='TaskTBL')
    op.drop_table('TaskTBL')
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_UserTBL_id'), table_name='UserTBL')
    op.drop_table('UserTBL')
    # ### end Alembic commands ###
